"""builder.py - merge src_dev/ into a single-file claw_se.py (internal tool, not shipped).

- Anchors src_dev/ via `__file__` (cwd-independent).
- Output written to Path.cwd() (respect the user; use --out to override).
- `python builder.py`            -> claw_se.py (single file)
- `python builder.py --exe`      -> also build claw_se.exe via PyInstaller (optional)

Never embeds secrets (.env) or runtime data (modules/**/data/). The dev-only
claw_se_main.py / claw_se_entry.py template are excluded from the payload.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC_DEV = ROOT / "src_dev"
ENTRY = SRC_DEV / "claw_se_entry.py"

_PAYLOAD_PLACEHOLDER = "_PAYLOAD: dict[str, str] = {}  # <-- builder.py replaces this line with the embedded file map"
_BANNER = "#!/usr/bin/env python3\n# claw_se.py - Claw_SE single-file build (generated by builder.py, do not edit)\n"

_EXCLUDED_RELS = {
    ".env",                 # secrets, never embedded
    "claw_se_main.py",      # dev-only entry
    "claw_se_entry.py",     # template used by this builder
}


def collect_payload() -> dict:
    """Collect all shippable src_dev files as {relative_posix_path: content}.

    Returns:
        Mapping of release-relative path -> file content.
    """
    payload: dict[str, str] = {}
    for path in sorted(SRC_DEV.rglob("*")):
        if path.is_dir():
            continue
        rel = path.relative_to(SRC_DEV).as_posix()
        if rel in _EXCLUDED_RELS:
            continue
        if "__pycache__" in rel or rel.endswith(".pyc"):
            continue
        if "/data/" in rel:  # runtime data (module data dirs), never embedded
            continue
        payload[rel] = path.read_text(encoding="utf-8")
    return payload


def build(output_dir: Path) -> Path:
    """Synthesize claw_se.py from src_dev/.

    Args:
        output_dir: directory for the output file (default cwd).

    Returns:
        The output claw_se.py path.

    Raises:
        RuntimeError: when the entry template placeholder is missing.
    """
    entry = ENTRY.read_text(encoding="utf-8")
    if _PAYLOAD_PLACEHOLDER not in entry:
        raise RuntimeError("claw_se_entry.py placeholder line not found; template changed?")
    payload = collect_payload()
    payload_block = json.dumps(payload, ensure_ascii=False, indent=2)
    entry = entry.replace(_PAYLOAD_PLACEHOLDER, f"_PAYLOAD = {payload_block}")

    output_dir.mkdir(parents=True, exist_ok=True)
    out = output_dir / "claw_se.py"
    content = _BANNER + f"# embedded files: {len(payload)}\n\n" + entry
    out.write_text(content, encoding="utf-8")
    print(f"[builder] wrote {out} ({len(content)} bytes, {len(payload)} embedded files)")
    return out


def build_exe(claw_se_py: Path) -> bool:
    """Build claw_se.exe via PyInstaller onefile (optional; needs PyInstaller)."""
    import importlib
    import subprocess
    try:
        importlib.import_module("PyInstaller")
    except ImportError:
        print("[builder] PyInstaller not installed; skipping claw_se.exe "
              "(pip install pyinstaller to enable).")
        return False
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile", "--console",
        "--name", "claw_se",
        "--hidden-import", "langchain_openai",
        "--hidden-import", "langchain_core",
        str(claw_se_py),
    ]
    print("[builder] running PyInstaller:", " ".join(cmd))
    subprocess.check_call(cmd)
    print("[builder] exe output: dist/claw_se(.exe)")
    return True


def main() -> None:
    """Builder CLI."""
    parser = argparse.ArgumentParser(description="Build the single-file claw_se.py from src_dev/.")
    parser.add_argument("--exe", action="store_true", help="also build claw_se.exe (PyInstaller)")
    parser.add_argument("--out", type=Path, default=None, help="output directory (default cwd)")
    args = parser.parse_args()

    output_dir = args.out or Path.cwd()
    claw_se_py = build(output_dir)
    if args.exe:
        build_exe(claw_se_py)


if __name__ == "__main__":
    main()
